<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vocabulary_model" nsURI="http:///com/graeditor/vocabulary_model.ecore"
    nsPrefix="com.graeditor.vocabulary_model">
  <eClassifiers xsi:type="ecore:EClass" name="AreaModule" eSuperTypes="#//VocabularyModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="VocabularyModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousModules" upperBound="-1"
        eType="#//VocabularyModule" eOpposite="#//VocabularyModule/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//VocabularyModule"
        eOpposite="#//VocabularyModule/previousModules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileModule" eSuperTypes="#//VocabularyModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileStackModule" eSuperTypes="#//VocabularyModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="PageModule" eSuperTypes="#//VocabularyModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="PageStackModule" eSuperTypes="#//VocabularyModule"/>
</ecore:EPackage>
