<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="component_model" nsURI="http:///com/graeditor/component_model.ecore"
    nsPrefix="com.graeditor.component_model">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousModules" eType="#//ComponentModule"
        eOpposite="#//ComponentModule/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//ComponentModule"
        eOpposite="#//ComponentModule/previousModules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseModule" eSuperTypes="#//ComponentModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="LittleComponentModule" eSuperTypes="#//ComponentModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="LittleFramworkModule" eSuperTypes="#//ComponentModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="LittleInterfaceModule" eSuperTypes="#//ComponentModule"/>
</ecore:EPackage>
