<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deployment_model" nsURI="http:///com/graeditor/deployment_model.ecore"
    nsPrefix="com.graeditor.deployment_model">
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousModules" eType="#//DeploymentModule"
        eOpposite="#//DeploymentModule/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//DeploymentModule"
        eOpposite="#//DeploymentModule/previousModules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceNodeModule" eSuperTypes="#//DeploymentModule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessorNodeModule" eSuperTypes="#//DeploymentModule"/>
</ecore:EPackage>
